[project]
name = "fantasy-stats"
version = "0.1.0"
description = "A site that compiles and performs analysis on cycling data"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "streamlit",
  "procyclingstats",
  "numpy",
  "pandas",
  "plotly",
  "statsmodels",
  "scipy"
]
